# Site settings
title: Alicia Morales Pearse
description: Web Developer
# baseurl: "/alipea" # the subpath of your site, e.g. /blog
# url: "http://aliciapearse.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alicia Morales Pearse
user_description:
user_title: Software Developer
email: hello@aliciapearse.com
twitter_username: alicia_pearse
github_username: /AliPea

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
