# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/blog/" # the subpath of your site, e.g. /blog
# url: "http://aliciapearse.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: alipea
user_description: After graduating with a B.A. in Political Economy from U.C. Berkeley and while working in financial services in London, I started coding in my spare time. I learned about programming by playing video games since I was young and always enjoyed the learning curve - it was rewarding and fun. I enjoy working with other smart and driven individuals who inspire me to be better. I go by this quote which sums it up; 'If you are the smartest person in the room, then you are in the wrong room.'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy
user_title: Web Developer
email: hello@aliciapearse.com
twitter_username: alicia_pearse
github_username: /AliPea

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
