# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alicia Pearse
user_description: After graduating with a B.A. in Political Economy from the U.C. Berkeley and working in financial services in London, Alicia began coding for fun and to learn the practical skill of making web applications. Having her roots in Costa Rica and recently working in England, Alicia offers diversity, experience and accounts with global perspective useful in problem solving beyond the IDE. Alicia is professional, goes above and beyond to meet her deliverables and enjoys being social. In her spare time she likes to read tech blogs, learn new technologies and play the flute. Alicia loves learning anything she doesn't know as long as it is interesting or useful and goes by this quote; 'If you are the smartest person in the room, then you are in the wrong room.'
user_title: Web Developer
email: hello@aliciapearse.com
twitter_username: alicia_pearse
github_username: /AliPea

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
